# Generated by Django 4.2.1 on 2023-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
