# Generated by Django 4.2 on 2023-06-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'Main'), ('2', 'Employer'), ('3', 'Employee')], default='3', max_length=8),
        ),
    ]
