# Generated by Django 4.2.1 on 2023-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestworker',
            name='task',
            field=models.CharField(default='default zone', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestworker',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requestworker',
            name='start_date',
            field=models.DateField(),
        ),
    ]
