# Generated by Django 4.2.1 on 2023-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0002_requestworker_task_alter_requestworker_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='account_type',
            field=models.CharField(blank=True, choices=[('1', 'Main'), ('2', 'Employer'), ('3', 'Employee')], default='3', max_length=1),
        ),
    ]
