# Generated by Django 4.2.1 on 2023-07-01 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0002_task_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now=True)),
                ('requseted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humanresources.employer')),
            ],
        ),
    ]
