# Generated by Django 4.2.1 on 2023-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0002_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
