# Generated by Django 4.2.1 on 2023-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0003_alter_email_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='account_type',
            field=models.CharField(blank=True, choices=[('1', 'Main'), ('3', 'Employer'), ('2', 'Employee')], default='2', max_length=1),
        ),
    ]
