# Generated by Django 4.2.1 on 2023-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0004_alter_email_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestworker',
            name='workers',
            field=models.ManyToManyField(to='humanresources.email'),
        ),
    ]
