# Generated by Django 4.2.1 on 2023-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0005_requestworker_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestworker',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requestworker',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to='humanresources.email'),
        ),
    ]
