# Generated by Django 4.2.1 on 2023-07-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0006_requestworker_accepted_alter_requestworker_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestworker',
            old_name='accepted',
            new_name='filled',
        ),
    ]
