# Generated by Django 4.2.1 on 2023-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresources', '0007_rename_accepted_requestworker_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
